services:
  admin_bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: admin_bot
    env_file:
      - .env
    networks:
      - shared_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin_bot.rule=Host(`api.rosdk.ru`) && PathPrefix(`/admin_bot`)"
      - "traefik.http.routers.admin_bot.entrypoints=websecure"
      - "traefik.http.routers.admin_bot.tls.certresolver=le"
      - "traefik.http.services.admin_bot.loadbalancer.server.port=8009"

networks:
  shared_network:
    external: true
