version: '3.8'

services:
  rsk_teams_app:
    build: .
    depends_on:
      rsk_teams_db:
        condition: service_healthy
    ports:
      - "8001:8001"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app_network

  rsk_teams_db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge